### ISSUE TITLE
Request to support Elasticsearch version 5.1.1 and 6.5.4

### ISSUE THREAD

**Issue by masykurm** [SeaseLtd/rated-ranking-evaluator#86]
Thanks for the great tools , after tried and ran the example I'm pretty sure and confidence it would be great help. However as per [1] , supported Elasticsearch version only 6.x above and has not reach 6.5.0. Currently we are running Elasticsearch 5.1.1, I'm afraid if with different elasticsearch version it would resulting different scoring and evaluation. 

it would be great help if RRE can support this version and 6.5.0 as well

Thanks and it is very great tools !

Links
[1] https://github.com/SeaseLtd/rated-ranking-evaluator/wiki/Supported%20Versions

**Comment by agazzarini** [comment]
Hi @masykurm the RRE maven artifacts has been refactored and uploaded, you can find the current supported versions in the page you mentioned above. 

Unfortunately, due to a set of breaking changes in ES API between 5.x and 6.x, we didn't include 5.1.1 in this first round; this is in plan, but at the moment you can only use 5.6.16 (the 5.x major version). 

Let me know if that can work for you. I'm closing this ticket, if you still need 5.1.1 I'll open a new ticket
