### ISSUE TITLE
Unresolved Maven dependency prevents using the external Elasticsearch plugin

### ISSUE THREAD

**Issue by ChristianBartl** [SeaseLtd/rated-ranking-evaluator#88]
Hi,

I wanted to try a RRE-setup with an external Elasticsearch but while using the **rre-maven-external-elasticsearch-plugin** I got the following error:

`[ERROR] Plugin io.sease:rre-maven-external-elasticsearch-plugin:6.3.2 or one of its dependencies could not be resolved: Could not find artifact io.sease:rre-maven-external-elasticsearch-plugin:jar:6.3.2 in sease (https://raw.github.com/SeaseLtd/rated-ranking-evaluator/mvn-repo) -> [Help 1]`

Andrea Gazzarini kindly wrote to me that the reason for that is: "The problem is that the external elasticsearch plugin has been contributed recently, and the maven repository hasn't been yet updated with all the available engine versions (Solr and Elasticsearch)." 

Is there a chance that the repo will be updated, or is there maybe a workaround or can I contribute myself?

Thanks for reading and I would be very thankful for maybe giving me a hint!

**Comment by agazzarini** [comment]
Hi Christian,
we are still deciding what is the best approach for updating and 
maintaining the maven repo; unfortunately it sounds like it won't be a 
quick decision, because within the team there are different opinions on 
that topic.

I suggest you to

  * clone the project
  * change the es version you want to use
  * build the project

That will install on your machine the required artifacts and since then, 
RRE will use them. This is the quickest way that comes on my mind.

If you need support I'm here, just give me a shout ;)

Cheers,

Andrea

**Comment by agazzarini** [comment]
Hi @ChristianBartl this has been fixed; if you retry with one of the versions listed here [1] everything should work. 

Best, 
Andrea

---

[1] https://github.com/SeaseLtd/rated-ranking-evaluator/wiki/Supported%20Versions
