### ISSUE TITLE
No errors shows in console when Solr cannot be reached

### ISSUE THREAD

**Issue by AlexAddisonLN** [SeaseLtd/rated-ranking-evaluator#91]
When Solr is not reachable (e.g. RRE is run in a sandboxed environment) RRE will appear to run incredibly quickly, and inform us at the end that no evaluations were performed. It will also generate an invalid Excel file if Excel report generation is set up.

**Comment by agazzarini** [comment]
Hi @AlexAddisonLN, many thanks for entering this. 
I assume you're talking about the external Solr (not the embedded one) right?

**Comment by AlexAddisonLN** [comment]
Yes, I am talking about the external Solr

**Comment by agazzarini** [comment]
I tried to reproduce your context; if Solr is not running I got this results: 

**External Solr Plugin**
```
[INFO ] *********************************
[INFO ] RRE: Index name => core1
[INFO ] RRE: ID Field name => id
[INFO ] Preparing platform for core1
[INFO ] RRE: Loading the Test Collection into External Apache Solr, configuration version v1.0
[INFO ] RRE: Loading the Test Collection into External Apache Solr, configuration version v1.1
[INFO ] RRE: External Apache Solr has been correctly loaded.
[INFO ] RRE: target versions are v1.0,v1.1
[INFO ] TOPIC: Fender basses
[INFO ] 	QUERY GROUP: The group tests several searches on the Fender brand
[INFO ] 		QUERY: fender
[INFO ] 		QUERY: fender Bass
[INFO ] 		QUERY: Fender
[INFO ] 	QUERY GROUP: Several searches on a given model (Jazz bass)
[INFO ] 		QUERY: jazz
[INFO ] 		QUERY: Jazz bass
[INFO ]   ... completed 0 / 5 evaluations ...
[INFO ] RRE: External Apache Solr Evaluation complete - preparing for shutdown
[WARN ] No queries recorded - returning empty evaluation
[INFO ] RRE: External Apache Solr Search Platform shutdown procedure executed.
[INFO ] RRE: Stopping persistence manager
```

The (Spreadsheet) Maven Report Plugin instead produces an empty excel. 
This behaviour is caused by the default evaluation manager which executes the queries in parallel and it doesn't block the evaluation if there's some error on a query. Unfortunately in the edge case when all queries fail (because Solr is not reachable) nothing is stopped and, as you said, the evaluation is incredibly quickly.

I'm not sure how to proceed because the asynchronous nature of the default evaluation manager. Do you expect everything is stopped in case of such error? Or another type of signal? 

@mattoscln any thoughts on this?

In the meantime, I'm going to push a small change in the Maven Report Plugin which makes sure that if there's no data, the report generation doesn't start at all. You can see that happening if there's the following line:
 
```
[INFO] No evaluation data has been generated - no reports will be produced.
```

**Comment by mattflax** [comment]
I think the best approach would be to do this in the SearchPlatform beforeStart method, at least for the external platforms. If we pass in the version manager, we can initialise the clients then, do a quick check (run a dummy query, perhaps) for each index, and throw an exception if none of the clients can connect.

This seems a bit cleaner than initialising the clients during the load() phase, as currently happens, and gives us a chance to stop before the query loop if there are no valid indexes available.

Does that sound sensible? I'm happy to implement it if you agree.

**Comment by agazzarini** [comment]
Hi @mattflax great idea, I completely agree. The beforeStart method seems the ideal place where to pu that change, and as you said, it makes sense especially for external platforms.

I'm already working on that, I'll show you the changes as soon as I have something "viewable", if you could have a look / tell me your thoughts it would be great. 

Once the draft will be ready we could even work together on that.

Thanks,
Andrea

**Comment by agazzarini** [comment]
@mattoscln after looking at the code, I think we could use the afterStart method instead of beforeStart. Just to make it consistent with the fact we are checking something that should be started.
Unfortunately, that method (the same is valid for the beforeStart) doesn't accept any parameter :( so a couple of options come in my mind:  

- move the afterStart call within the ratings loop and pass the required parameters (e.g. indexName) 

```
            // from here...
            platform.afterStart();

            final Evaluation evaluation = new Evaluation();

            ratings().forEach(ratingsNode -> {
                LOGGER.info("RRE: Ratings Set processing starts");

                final String indexName =
                        requireNonNull(
                                ratingsNode.get(INDEX_NAME),
                                "WARNING!!! \"" + INDEX_NAME + "\" attribute not found!").asText();

              // ...to here (with additional parameters)
             platform.afterStart(indexName);
```

- introduce a new lifecycle method in the SearchPlatform (e.g. check):

```
            platform.afterStart();

            final Evaluation evaluation = new Evaluation();

            ratings().forEach(ratingsNode -> {
                LOGGER.info("RRE: Ratings Set processing starts");

                final String indexName =
                        requireNonNull(
                                ratingsNode.get(INDEX_NAME),
                                "WARNING!!! \"" + INDEX_NAME + "\" attribute not found!").asText();

             platform.check(indexName);
```

**Comment by mattflax** [comment]
Hi Andrea,

I don't think we should move afterStart() into the ratings loop - it's a start-up method, so surely it should run once.

Adding a check in load() seems the obvious compromise, since that is where the clients are currently initialised - adding a check for the index there should be simple enough, and we could throw an UnableToLoadDataException. Depending on whether or not we catch that (since it's a RuntimeException), we could either break out of the whole application or skip that index and carry on.

Do we want to break the application if one index cannot be reached, or to carry on and hope we can reach the other indexes? It does seem like it should be a major failure if an index is unreachable, though it would be good to handle it gracefully.

**Comment by agazzarini** [comment]
Closed. See https://github.com/SeaseLtd/rated-ranking-evaluator/pull/126
